apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: brp-scan-worker-hpa
  namespace: brp-cyber
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: brp-scan-worker
  minReplicas: 2
  maxReplicas: 200
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
